In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


class LinearRegression():

    def __init__(self, learning_rate, iterations):
        self.learning_rate = learning_rate
        self.iterations = iterations
    
    def calculateCost(self):
        diff = np.power((self.X.dot(self.theta.T) - self.Y), 2)
        return np.sum(diff) / (2 * self.m)


    def gradient_descent(self, X, Y):

        self.m, self.n = X.shape
        self.theta = np.matrix(np.zeros(self.n))

        self.X = np.matrix(X.values)
        self.Y = np.matrix(Y.values)
        self.cost = []

        for i in range(self.iterations):
            self.update_thetas()
            self.cost.append(self.calculateCost())
        return self


    def update_thetas(self):
        
        self.h = self.predicted_Y()
#         print(self.X.dot( self.Y - self.h ))
        print(self.X)
        print(self.Y)
        print(self.h)
#         self.theta = self.theta - self.learning_rate * (  self.X.dot( self.Y.T - self.h ) / self.m )
        return self

    
    def predicted_Y(self):
        return self.X.dot(self.theta.T)





In [2]:
# !pip install pandas

In [ ]:
house_data = pd.read_csv("house_data.csv")
house_data.insert(0,"Ones", 1)
# house_data
flag = True
if flag:
    X = house_data[['Ones','sqft_living']]
else:
    X = house_data.loc[:,['Ones','grade', 'bathrooms', 'lat', 'sqft_living', 'view']]
Y = house_data['price']

learning_rate = 0.01
iterations = 1

linearModel = LinearRegression(learning_rate , iterations)
linearModel.gradient_descent(X,Y)
# linearModel.theta


[[   1 1180]
 [   1 2570]
 [   1  770]
 ...
 [   1 1020]
 [   1 1600]
 [   1 1020]]
[[221900. 538000. 180000. ... 402101. 400000. 325000.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
